# MISC
NAME = mapillary_tools

# BOOT
RUN_DIR=/mapillary_source
RUN_CMD=script/run upload

export

DOCKER_CONTEXT=../

MAPILLARY_CLUSTER_DIR ?= /opt/mapillary_cluster
include $(MAPILLARY_CLUSTER_DIR)/build/app/Makefile
