#!/bin/bash
# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the BSD license found in the
# LICENSE file in the root directory of this source tree.

set -e

OS=linux

# build
mkdir -p dist
rm -rf dist/${OS}
pyinstaller --version
pyinstaller --noconfirm --distpath dist/${OS} pyinstaller/mapillary_tools.spec
pyinstaller --noconfirm --distpath dist/${OS} pyinstaller/mapillary_tools_folder.spec

# check
SOURCE=dist/${OS}/mapillary_tools
$SOURCE --version
VERSION=$($SOURCE --version | awk '{print $3}')
ARCH=$(uname -m)
TARGET=dist/releases/mapillary_tools-${VERSION}-${OS}-${ARCH}
pyi-archive_viewer --list "$SOURCE"

# package
mkdir -p dist/releases
cp "$SOURCE" "$TARGET"

# sha256 (disabled because github release page shows checksums)
if [ "" ]; then
    TARGET_BASENAME=$(basename "$TARGET")
    # to produce "HASH mapillary_toos" instead of "HASH dist/releases/mapillary_tools"
    cd dist/releases
    shasum -a256 "$TARGET_BASENAME" | tee "${TARGET_BASENAME}.sha256.txt"
    cd ../../
fi

# check
FOLDER=dist/${OS}/mapillary_tools_folder
SOURCE=dist/${OS}/mapillary_tools_folder/mapillary_tools
$SOURCE --version
VERSION=$($SOURCE --version | awk '{print $3}')
ARCH=$(uname -m)
TARGET=dist/releases/mapillary_tools-folder-${VERSION}-${OS}-${ARCH}

# package
mkdir -p dist/releases
cd dist/${OS}/
zip -r ../../"$TARGET" mapillary_tools_folder
cd ../../

# sha256 (disabled because github release page shows checksums)
if [ "" ]; then
    TARGET_BASENAME=$(basename "$TARGET")
    # to produce "HASH mapillary_tools" instead of "HASH dist/releases/mapillary_tools"
    cd dist/releases
    shasum -a256 "$TARGET_BASENAME" | tee "${TARGET_BASENAME}.sha256.txt"
    cd ../../
fi

# summary
ls -l dist/releases
