#!/bin/bash
set -e

OS=linux

# build
mkdir -p dist
rm -rf dist/${OS}
pyinstaller --version
pyinstaller --noconfirm --distpath dist/${OS} mapillary_tools.spec

# check
SOURCE=dist/${OS}/mapillary_tools
$SOURCE --version
VERSION=$($SOURCE --version | awk '{print $3}')
ARCH=$(uname -m)
TARGET=dist/releases/mapillary_tools-${VERSION}-${OS}-${ARCH}

# package
mkdir -p dist/releases
cp "$SOURCE" "$TARGET"

# sha256
TARGET_BASENAME=$(basename "$TARGET")
# to produce "HASH mapillary_toos" instead of "HASH dist/releases/mapillary_tools"
cd dist/releases
shasum -a256 "$TARGET_BASENAME" | tee "${TARGET_BASENAME}.sha256.txt"
cd ../../

# summary
ls -l dist/releases
