#!/bin/bash

/usr/local/bin/virtualenv venv
source venv/bin/activate
pip install pyinstaller 
pip install -r requirements.txt

pyinstaller --distpath dist/osx --onefile --windowed mapillary_tools.spec --osx-bundle-identifier mapillary_tools

deactivate

ls -la publish/

mkdir -p publish/

ls -la publish/

mv dist/osx publish

ls -la publish/
