#!/bin/bash
set -e

SOURCE=dist/osx/mapillary_tools.app/Contents/MacOS/mapillary_tools
TARGET=dist/mapillary_tools_osx.zip

mkdir -p dist
rm -rf dist/osx
pyinstaller --noconfirm --distpath dist/osx --onefile --windowed mapillary_tools.spec --osx-bundle-identifier mapillary_tools
zip -j "$TARGET" "$SOURCE" README_osx_package.txt
