#!/bin/bash
aws s3 cp publish/win/mapillary_tools.exe s3://mapillary-tools/latest/mapillary_tools.exe

zip -r mapillary_tools.zip publish/osx/mapillary_tools.app/
aws s3 cp mapillary_tools.zip s3://mapillary-tools/latest/mapillary_tools.zip
