#!/bin/bash

source mtc_init default

if [ "$1" = "upload" ];
then
    mtc cluster wait $S3_WAIT
    mtc cluster wait $API_WAIT
    mtc cluster wait $API_PROXY_WAIT
    sleep 30
    while :
    do
        mapillary_tools upload --import_path tests/integration/mapillary_tools_upload_provider/data/images/
        sleep 60
    done
elif [ $1 = "process" ];
then
    mtc cluster wait $S3_WAIT
    mtc cluster wait $API_WAIT
    mtc cluster wait $API_PROXY_WAIT
    sleep 30
    while :
    do
        echo "Processing images..."
        mapillary_tools process --import_path tests/integration/mapillary_tools_process_images_provider/data/images/ --advanced --user_name mapillary_user
        sleep 3
        echo "Uploading images..."
        mapillary_tools upload --import_path tests/integration/mapillary_tools_process_images_provider/data/images/
        sleep 30
    done
fi
